hnuti-brontosaurus/bis

- frontend/src/app/services/bis.ts
- frontend/src/components/SelectUsers/SelectUsers.tsx
- frontend/src/hooks/readFullEvent.ts
- frontend/src/hooks/readUnknownAndFullUsers.ts
- frontend/src/org/components/EventForm/steps/registration/AddParticipantModal.tsx
- frontend/src/org/pages/ViewEvent/ViewEvent.tsx
https://trello.com/c/VzEosty7/533-zobrazen%C3%AD-jen-20-%C3%BA%C4%8Dastn%C3%ADk%C5%AF-v-seznamu
> Fix participants limited to 20

- frontend/src/org/components/EventForm/steps/RegistrationStep.tsx
> feature-infobox for electronic application

- frontend/src/org/pages/CloseEvent/EvidenceStep.tsx
New section for follow up email
https://trello.com/c/pkhbPRuc
> feature-event-follow-up-link

- frontend/src/org/components/EventForm/steps/registration/Participants.tsx
https://trello.com/c/xK6yKRc0/530-export-do-pdf-prezen%C4%8Dn%C3%AD-listiny-i-pro-seznam-%C3%BA%C4%8Dastn%C3%ADk%C5%AF
> pdf export of attendees added

- frontend/README.md
- frontend/src/org/components/EventForm/steps/ParticipantsStep.module.scss
- frontend/src/org/components/EventForm/steps/registration/Applications.tsx
- frontend/src/org/components/EventForm/steps/registration/NewApplicationModal.module.scss
- frontend/src/org/components/EventForm/steps/registration/Participants.tsx
- frontend/src/org/components/EventForm/steps/registration/ShowApplicationModal.tsx
https://trello.com/c/VkkdmUiH/487-zobrazit-kvalifikace-pokud-rozkliknu-u%C5%BEivatele-v-seznamu-p%C5%99ihl%C3%A1%C5%A1en%C3%BDch
> Info added to applications

- frontend/cypress/fixtures/event.json
- frontend/cypress/fixtures/simpleEvent.json
- frontend/src/app/services/bis.ts
- frontend/src/app/services/bisTypes.ts
- frontend/src/app/services/testApi.ts
- frontend/src/components/FormLayout/FormLayout.module.scss
- frontend/src/org/components/EventForm/EventForm.tsx
- frontend/src/org/components/EventForm/steps/BasicInfoStep.tsx
https://trello.com/c/Pk1lnU1h/575-pridani-stitkutagu
> Feature event tags

- frontend/src/components/UserForm/UserForm.tsx
- frontend/src/org/components/EventForm/steps/ParticipantsStep.tsx
- frontend/src/org/components/EventForm/steps/registration/AddParticipantModal.tsx
- frontend/src/org/components/EventForm/steps/registration/Applications.tsx
https://trello.com/c/JhCorADo/527-p%C5%99edvyplnit-profil-z-p%C5%99ihl%C3%A1%C5%A1ky
> user prefilled from application in the form

- frontend/src/components/Steps/Steps.tsx
- frontend/src/utils/useKeyDown.ts
https://trello.com/c/oHEoXCQS/464-enter-u-zadavani-nove-akce
> enter working as arrow in creating event added

- frontend/src/layout/Layout.module.scss
- frontend/src/org/pages/ViewEvent/ViewEvent.module.scss
- frontend/src/org/pages/ViewEvent/ViewEvent.tsx
> event display redesign

- frontend/src/org/components/EventForm/steps/BasicInfoStep.tsx
https://trello.com/c/K73lBNko/408-upravit-v%C3%BDb%C4%9Br-polo%C5%BEek
> admin unit name shortened

- frontend/src/org/components/EventForm/steps/registration/AddParticipantModal.tsx
- frontend/src/org/components/EventForm/steps/registration/NewApplicationModal.module.scss
https://trello.com/c/ZWLpEZ9R/466-presun-uzivatele-ze-seznamu-prihlasenych-do-seznamu-ucastniku
> Feature add participant icons

- frontend/src/org/components/EventForm/steps/ParticipantsStep.module.scss
- frontend/src/org/components/EventForm/steps/ParticipantsStep.tsx
- frontend/src/org/components/EventForm/steps/registration/ParticipantsStats.tsx
https://trello.com/c/Te4IGDjA/465-statistika-ucastniku
> Feature participants stats

- frontend/cypress/e2e/createEvent.cy.ts
- frontend/src/org/components/EventForm/EventForm.tsx
- frontend/src/org/components/EventForm/steps/IntendedForStep.tsx
- frontend/src/utils/validationMessages.tsx
https://trello.com/c/EruEj2eA/480-vip-propagace-nepovinn%C3%A1-a-povinn%C3%A1-pro-t%C3%A1bor-atd
> vip propagation updated

- frontend/cypress/e2e/closeEvent.cy.ts
- frontend/cypress/e2e/createEvent.cy.ts
- frontend/src/components/SelectLocation/SelectLocation.tsx
- frontend/src/components/SelectUsers/SelectUsers.tsx
- frontend/src/hooks/rejectApplication.tsx
- frontend/src/hooks/removeEvent.tsx
- frontend/src/hooks/removeOpportunity.tsx
- frontend/src/hooks/useCancelEvent.tsx
- frontend/src/hooks/useConfirmWithModal.tsx
- frontend/src/layout/AdminOutlet.tsx
- frontend/src/org/components/EventForm/steps/registration/AddParticipantModal.tsx
- frontend/src/org/components/EventForm/steps/registration/Applications.tsx
- frontend/src/org/components/EventForm/steps/registration/BirthdayInputCheck.tsx
- frontend/src/org/components/EventForm/steps/registration/Participants.tsx
- frontend/src/pages/NotFound.tsx
https://trello.com/c/dD0bLWGg/513-sjednotit-formulaci-kontextov%C3%BDch-n%C3%A1pov%C4%9Bd-v-tabulce-p%C5%99ihl%C3%A1%C5%A1ek
> Update button text infinitive

- frontend/src/components/ListHeader/ListHeader.module.scss
- frontend/src/components/ListHeader/ListHeader.tsx
- frontend/src/org/pages/OpportunityList/OpportunityList.tsx
https://trello.com/c/OofhlCAC/476-p%C5%99idat-odkaz-na-formul%C3%A1%C5%99-chci-se-zapojit
> participate link added

- frontend/src/org/pages/CloseEvent/CloseEvent.tsx
> owl text in CloseEvent updated

- frontend/src/components/Steps/Steps.module.scss
> navigation arrows redesign

- frontend/src/components/UserForm/UserForm.tsx
https://trello.com/c/JhCorADo/527-p%C5%99edvyplnit-profil-z-p%C5%99ihl%C3%A1%C5%A1ky
info missing for child fixed
> user from application missing child info fixed

- frontend/src/org/components/EventForm/steps/registration/ShowApplicationModal.tsx
- frontend/src/pages/SendResetPasswordLink.tsx
https://trello.com/c/oicqgxjZ/601-mo%C5%BEn%C3%A1-bug
> hyphen added to allowed symbols in email

- frontend/cypress/e2e/createEvent.cy.ts
- frontend/src/org/components/EventForm/steps/IntendedForStep.tsx
https://trello.com/c/EruEj2eA/480-vip-propagace-nepovinn%C3%A1-a-povinn%C3%A1-pro-t%C3%A1bor-atd
fixing the missing star and error message
> vip propagation missing error messages fixed

- frontend/src/org/pages/CloseEvent/CloseEventForm.tsx
https://trello.com/c/upsboBZF/561-asi-bug-n%C4%9Bkter%C3%A9-akce-nejdou-ulo%C5%BEit-v-pr%C5%AFb%C4%9Bhu-vypl%C5%88ov%C3%A1n%C3%AD
> saving after event withou closing allowed

- frontend/src/org/pages/CloseEvent/CloseEvent.tsx
> fix - after event message changed

- frontend/src/org/pages/ViewEvent/ViewEvent.tsx
https://trello.com/c/qg2xlcvD/632-po-akci-prepsat-na-%C3%BA%C4%8Dastn%C3%ADci-evidence-akce
> fix - after event button

- frontend/src/features/systemMessage/SystemMessage.tsx
> fix - error message timeout

- frontend/src/components/Steps/Steps.tsx
https://trello.com/c/r2Ettr1X/669-%C5%A1ipky-p%C5%99i-editaci-textu-posouvaj%C3%AD-mezi-str%C3%A1nkami
> unnecessary key event removed

- frontend/src/org/components/EventForm/steps/ParticipantsStep.tsx
https://trello.com/c/0kJQhwdz/633-bug-neulozili-se-ucastnici
> bug fix attempt

- frontend/cypress/e2e/login.cy.ts
- frontend/src/layout/Header.tsx
https://trello.com/c/8Lljpsn7/584-zv%C3%BDraznit-proklik-na-admin-profil
> admin profile click updated

- frontend/src/org/components/EventForm/steps/ParticipantsStep.module.scss
- frontend/src/org/components/EventForm/steps/ParticipantsStep.tsx
- frontend/src/org/components/EventForm/steps/registration/ParticipantsStats.tsx
https://trello.com/c/bXoeyaHJ/655-vylep%C5%A1it-statistiku
> Feature split statistics

- frontend/src/org/components/EventForm/steps/ParticipantsStep.module.scss
https://trello.com/c/vFf38bsd/609-zv%C3%BDraznit-r%C3%A1me%C4%8Dek-na-vyhled%C3%A1v%C3%A1n%C3%AD-u%C5%BEivatele-u-seznamu-%C3%BA%C4%8Dastn%C3%ADk%C5%AF
> participants select redesign

- frontend/src/org/pages/CloseEvent/ParticipantsStep.tsx
> feat: show clarification on participants number for events with multiple subevents

- frontend/src/app/services/bisTypes.ts
- frontend/src/components/TableCellIconButton/TableCellIconButton.tsx
- frontend/src/hooks/readFullEvent.ts
- frontend/src/org/components/EventForm/EventForm.tsx
- frontend/src/org/components/EventForm/steps/ParticipantsStep.module.scss
- frontend/src/org/components/EventForm/steps/ParticipantsStep.tsx
- frontend/src/org/components/EventForm/steps/registration/Applications.tsx
- frontend/src/org/components/EventForm/steps/registration/NewApplicationModal.tsx
- frontend/src/org/components/EventForm/steps/registration/Participants.tsx
- frontend/src/org/components/EventForm/steps/registration/ParticipantsStats.tsx
- frontend/src/org/pages/CloseEvent/CloseEvent.tsx
- frontend/src/org/pages/CloseEvent/CloseEventForm.tsx
- frontend/src/org/pages/CloseEvent/ParticipantsStep.tsx
- frontend/src/org/pages/EventApplications.tsx
- frontend/src/org/pages/UpdateEvent.tsx
- frontend/src/org/pages/ViewEvent/ViewEvent.tsx
> Feature extended application table

- frontend/src/org/components/EventForm/steps/registration/ShowApplicationModal.tsx
> feat: added note from application form to application detail

- frontend/src/org/components/EventForm/steps/IntendedForStep.tsx
> change "100" to "1 000"

- frontend/cypress/e2e/closeEvent.cy.ts
- frontend/src/org/components/EventForm/steps/registration/Participants.tsx
- frontend/src/org/components/ImportParticipants/ImportParticipants.tsx
> Fix: hide import button

- frontend/src/components/ImageUpload/ImageUpload.tsx
https://trello.com/c/ca1emwlU
Fotky z iPhonu nakonec nepodporujeme, protože je to složité a budeme se jim věnovat v budoucnosti.
> Fix upload pdf

- frontend/src/hooks/useAllowedToCreateEvent.ts
- frontend/src/org/components/EventForm/steps/OrganizerStep.tsx
- frontend/src/org/utils/validateQualifications.ts
> Fix main organizer qualification date

- frontend/src/org/pages/CloseEvent/CloseEventForm.tsx
- frontend/src/org/pages/CloseEvent/EvidenceStep.module.scss
- frontend/src/org/pages/CloseEvent/EvidenceStep.tsx
- frontend/src/org/pages/CloseEvent/ParticipantsStep.module.scss
- frontend/src/org/pages/CloseEvent/ParticipantsStep.tsx
> feat: worked hours note for events w/ multiple subevents

- frontend/src/org/pages/CloseEvent/CloseEvent.tsx
this would lead to newly added entities (photos, inquiries) to multiplicate
> fix: disallow submitting close event form multiple times

- frontend/src/org/components/EventForm/steps/ParticipantsStep.module.scss
- frontend/src/org/components/EventForm/steps/registration/ShowApplicationModal.tsx
https://trello.com/c/R4PiN9IU/769-hez%C4%8D%C3%AD-styl-p%C3%ADsma-po-rozkliknut%C3%AD-p%C5%99ihl%C3%A1%C5%A1ky
přestylovala jsem jen tu požadovanou část ze screenshotu z Trella. Přijde mi, že větší problém je ten suchý výpis pod tím (který se zobrazuje u některých přihlášek), kde to není vyřešené vůbec, ale to není součástí úkolu.
> better styling for application modal

- frontend/src/components/ImageUpload/ImageUpload.tsx
- frontend/src/org/pages/CloseEvent/CloseEvent.tsx
- frontend/src/org/pages/CloseEvent/EvidenceStep.tsx
https://trello.com/c/ZhMoSwEt
Už se s tím file uploadem špatně pracovalo, tak jsem ho celý přepsal.
Funkčně jde jinak o to, že do formuláře zavádím doplňkové pole `thumbnail` obsahující odkaz na malou fotku (generuje backend), jen je třeba ho, když uživatel nahraje jinou fotku, změnit (aby se pořád neukazovala fotka z backendu). Na to je tam ten `useEffect`, což by měla být plus mínus oficiální cesta, jak dělat závislá pole (viz https://github.com/react-hook-form/react-hook-form/issues/6009#issuecomment-962518944) -- teda, pokud existuje lepší, tak sem s ní.
> Feature show thumbnails

- frontend/src/utils/getRequiredFeedbackInquiries.ts
> fix typos in feedback form

- frontend/src/org/components/EventForm/steps/registration/Participants.tsx
- frontend/src/org/components/EventForm/steps/registration/useExportParticipantsList.ts
> fix: export participants to pdf (not only orgs)

- frontend/src/org/pages/CloseEvent/CloseEvent.tsx
this should solve partial initialization
> fix: better default value setting for feedback form
